#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Provisiona la infraestructura manual del pipeline AFK (T1, #17):
# GitHub App interna + instalación + clave privada + secrets/vars de Actions.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Set TOTAL_STAGES to match the stages you write.
#
# Helpers del pipeline AFK (T1 #17) — NO están en la librería del template:
#   secure_env      — chmod 600 sobre ENV_FILE tras cada escritura.
#   set_secret_file — inyecta un archivo (PEM multilínea) vía stdin a gh
#                     secret set, preservando los saltos de línea (PKCS#1/#8).
#   secret_exists   — consulta gh secret list para no sobrescribir en re-runs.
#   preflight       — fail rápido si falta gh o no hay sesión.
# ──────────────────────────────────────────────────────────────────────────

REPO="mauriciosoyastor/embodied-ai"

# Corrección 1: el .env local nunca queda sin restricciones de acceso.
secure_env() {
  [[ -f "$ENV_FILE" ]] && chmod 600 "$ENV_FILE"
  printf '  %s✓ chmod 600%s %s\n' "$GREEN" "$RESET" "$ENV_FILE"
}

# Corrección 2: llaves multilínea (PEM) por stdin directo, nunca por --body.
set_secret_file() {
  local name="$1" file="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh secret set "$name" < "$file" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s (desde %s)\n' "$GREEN" "$RESET" "$name" "$file"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name < $file)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# Corrección 4: re-ejecución segura — no sobrescribe secrets ya presentes.
secret_exists() {
  gh secret list --repo "$REPO" 2>/dev/null | grep -qE "^${1}\s"
}

# Corrección 3: fail rápido antes de pedir datos al usuario.
preflight() {
  _clear
  printf '\n%s%s▸ Pre-flight checks%s\n' "$BOLD" "$BLUE" "$RESET"
  if ! command -v gh >/dev/null 2>&1; then
    warn "gh CLI no está instalado. Instálalo desde https://cli.github.com y vuelve a correr."
    exit 1
  fi
  printf '  %s✓ gh instalado%s\n' "$GREEN" "$RESET"
  if ! gh auth status >/dev/null 2>&1; then
    warn "gh no está autenticado. Corre 'gh auth login' y vuelve a correr."
    exit 1
  fi
  printf '  %s✓ gh autenticado%s\n' "$GREEN" "$RESET"
  if ! gh repo view "$REPO" >/dev/null 2>&1; then
    warn "No hay acceso de lectura/escritura al repo $REPO."
    exit 1
  fi
  printf '  %s✓ acceso al repo %s%s\n' "$GREEN" "$RESET" "$REPO"
  pause "Pre-flight OK — continuar"
}

TOTAL_STAGES=4

banner "Pipeline AFK — provisioning (GitHub App + secrets)"

preflight

# ── Stage 1: registrar la GitHub App y capturar el Client ID ───────────────
stage "Registrar GitHub App"
say "Creamos la app interna con permisos acotados (R2/D1)."
open_url "https://github.com/settings/apps/new"
step "GitHub App name: elegí un nombre corto (ej. 'embodied-ai-agent'). Anotalo, lo vas a necesitar."
step "Homepage URL: pegá la URL del repo: https://github.com/$REPO"
step "Webhook: deseleccioná 'Active' (no necesitamos webhooks)."
step "Permissions → Repository permissions:"
step "  • Contents: Read & write"
step "  • Pull requests: Read & write"
step "  • Issues: Read & write"
step "  • Checks: Read-only"
step "  • Metadata queda Read-only (obligatorio, no lo cambies)"
step "Where can this GitHub App be installed?: 'Only on this account'."
step "Click 'Create GitHub App'."
say "Tras crearla GitHub te redirige a la página de la app. Copiá el Client ID."
ask APP_CLIENT_ID "Paste the Client ID:"
if [[ -z "$APP_CLIENT_ID" ]]; then
  warn "Client ID vacío — sin él no podemos seguir. Reejecutá esta etapa."
  exit 1
fi
write_env APP_CLIENT_ID "$APP_CLIENT_ID"
secure_env
set_var APP_CLIENT_ID "$APP_CLIENT_ID"

# ── Stage 2: generar la clave privada (PEM) e inyectarla por stdin ─────────
stage "Clave privada (PEM)"
say "El PEM es multilínea (PKCS#1/#8): se inyecta por redirección de archivo, nunca por variable."
say "En la página de la app, en la sección 'Private keys', click en 'Generate a private key'."
step "Se descarga un archivo .pem a tu máquina (ej. emb...private-key.pem)."
step "Movelo a una ruta fija y segura (fuera del repo), ej. ~/.ssh/embodied-ai-agent.pem"
step "NO lo commitees ni lo pegues en el repo."
ask APP_PRIVATE_KEY_PATH "Path del archivo .pem descargado:"
if [[ -z "$APP_PRIVATE_KEY_PATH" ]]; then
  warn "Sin ruta no podemos continuar."
  exit 1
fi
if [[ ! -f "$APP_PRIVATE_KEY_PATH" ]]; then
  warn "El archivo '$APP_PRIVATE_KEY_PATH' no existe. Verificá la ruta y reejecutá."
  exit 1
fi
printf '  %s✓ archivo PEM encontrado%s\n' "$GREEN" "$RESET"
if secret_exists APP_PRIVATE_KEY; then
  warn "El secret APP_PRIVATE_KEY ya existe — lo dejamos intacto (re-run seguro)."
else
  set_secret_file APP_PRIVATE_KEY "$APP_PRIVATE_KEY_PATH"
fi
write_env APP_PRIVATE_KEY_PATH "$APP_PRIVATE_KEY_PATH"
secure_env

# ── Stage 3: instalar la app en el repo ────────────────────────────────────
stage "Instalar la app en el repo"
say "La app debe instalarse para poder emitir tokens de instalación."
open_url "https://github.com/settings/apps"
step "Junto a tu app, click 'Edit'."
step "En el menú lateral, click 'Install App'."
step "En la página de instalación, elegí 'Only select repositories'."
step "Seleccioná únicamente '$REPO'."
step "Click 'Install'."
pause "Confirmá que la app quedó instalada en $REPO"

# ── Stage 4: API key de Anthropic ──────────────────────────────────────────
stage "API key de Anthropic"
say "El coder y el reviewer se autentican con ANTHROPIC_API_KEY."
open_url "https://console.anthropic.com/settings/keys"
step "Creá una API key nueva (o usá una existente) y copiala."
step "Tratá la key como secreto: no la expongas en chats, logs ni commits."
ask_secret ANTHROPIC_API_KEY "Paste the Anthropic API key (sk-ant-...):"
if [[ -z "$ANTHROPIC_API_KEY" ]]; then
  warn "API key vacía — sin ella el pipeline no puede correr."
  exit 1
fi
write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
secure_env
if secret_exists ANTHROPIC_API_KEY; then
  warn "El secret ANTHROPIC_API_KEY ya existe — lo dejamos intacto (re-run seguro)."
else
  set_secret ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
fi

finish
say ""
say "Próximo paso: etiquetar un issue canario con 'ready-for-agent' y correr T3 (#19)."
say "Para verificar secrets/vars:  gh secret list --repo $REPO && gh variable list --repo $REPO"
